doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8

        url: '%env(resolve:DATABASE_URL)%'

        types:
            sale_cashbox_timezone: 'App\Module\Sale\Entity\Cashbox\TimezoneType'
            sale_receipts_number: 'App\Module\Sale\Entity\Receipt\NumberType'
            sale_receipts_total: 'App\Module\Sale\Entity\Receipt\TotalType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Sale:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Sale/Entity'
                prefix: 'App\Module\Sale\Entity'
                alias: App
